Add v.0.2 to variable support for qmail-configurator

diff --git a/scripts/qmail-configurator b/scripts/qmail-configurator
--- a/scripts/qmail-configurator
+++ b/scripts/qmail-configurator
@@ -4,6 +4,23 @@ PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
 source /scripts/env
 
 case "$1" in
+  init-fqdn)
+      FQDN=${QMAIL_HOSTNAME}
+      if [[ -n "$FQDN" ]]; then
+          VALIDFQDN='^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$';
+          if echo "$FQDN" |egrep -q "$VALIDFQDN"; then
+              echo "$FQDN" | tee ${QMAIL_HOME}/control/me ${QMAIL_HOME}/control/locals ${QMAIL_HOME}/control/rcpthosts >/dev/null
+          else
+                echo "FQDN is not in valid form; setting as mx.domain.local"
+                FQDN="mx.domain.local"
+                echo "$FQDN" | tee ${QMAIL_HOME}/control/me ${QMAIL_HOME}/control/locals ${QMAIL_HOME}/control/rcpthosts >/dev/null
+          fi
+      else
+            echo "FQDN is not provided; setting as mx.domain.local"
+            FQDN="mx.domain.local"
+            echo "$FQDN" | tee ${QMAIL_HOME}/control/me ${QMAIL_HOME}/control/locals ${QMAIL_HOME}/control/rcpthosts >/dev/null
+      fi
+      ;;
   set-fqdn)
       FQDN="$2"
       if [[ -n "$FQDN" ]]; then
@@ -33,14 +50,32 @@ case "$1" in
       echo "##############"
       sed "s/:allow.*//" /etc/tcp.smtp
       ;;
-  add-relay)
-      IPRANGE="$2"
-      if [[ -n "$IPRANGE" ]]; then
+  init-relay)
+      if [[ -n "$RELAYIP" ]]; then
           VALIDIPRANGE='(^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){1,3}$)';
-          if echo "$IPRANGE" |egrep -q "$VALIDIPRANGE"; then
-              echo "$IPRANGE":allow,RELAYCLIENT=\"\" >> /etc/tcp.smtp
+          if echo "$RELAYIP" |egrep -q "$VALIDIPRANGE"; then
+              echo "$RELAYIP":allow,RELAYCLIENT=\"\" >> /etc/tcp.smtp
               qmailctl cdb
-              echo "Relay has been granted for "$IPRANGE""
+              echo "Relay has been granted for "$RELAYIP""
+          else
+             echo "Usage:  qmail-configurator add-relay "ip|range""
+             echo "Eg:     qmail-configurator add-relay 1.2.3.4 or 1.2.3."
+             exit 1
+          fi
+      else
+          echo "Usage:  qmail-configurator add-relay "ip|range""
+          echo "Eg:     qmail-configurator add-relay 1.2.3.4 or 1.2.3."
+          exit 1
+      fi
+      ;;
+  add-relay)
+      RELAYIP="$2"
+      if [[ -n "$RELAYIP" ]]; then
+          VALIDIPRANGE='(^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){1,3}$)';
+          if echo "$RELAYIP" |egrep -q "$VALIDIPRANGE"; then
+              echo "$RELAYIP":allow,RELAYCLIENT=\"\" >> /etc/tcp.smtp
+              qmailctl cdb
+              echo "Relay has been granted for "$RELAYIP""
           else
              echo "Usage:  qmail-configurator add-relay "ip|range""
              echo "Eg:     qmail-configurator add-relay 1.2.3.4 or 1.2.3."
@@ -53,20 +88,20 @@ case "$1" in
       fi
       ;;
   del-relay)
-      IPRANGE="$2"
-      if [[ -n "$IPRANGE" ]]; then
+      RELAYIP="$2"
+      if [[ -n "$RELAYIP" ]]; then
           VALIDIPRANGE='(^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){1,3}$)';
-          if echo "$IPRANGE" |egrep -q "$VALIDIPRANGE"; then
-              RANGEPATTETN="^$IPRANGE:allow,"
+          if echo "$RELAYIP" |egrep -q "$VALIDIPRANGE"; then
+              RANGEPATTETN="^$RELAYIP:allow,"
               egrep "$RANGEPATTETN" /etc/tcp.smtp >/dev/null
 
               if [ $? -eq 0 ]; then
-                sed -i -e "/^$IPRANGE:allow,/d" /etc/tcp.smtp
+                sed -i -e "/^$RELAYIP:allow,/d" /etc/tcp.smtp
                 qmailctl cdb
-                echo "Relay has been removed for "$IPRANGE""
+                echo "Relay has been removed for "$RELAYIP""
               else
 
-                echo "Relay not found for $IPRANGE"
+                echo "Relay not found for $RELAYIP"
                 echo ""
                 echo "Here are your current relay clients:"
                 sed "s/:allow.*//" /etc/tcp.smtp
